== How to run the tests

The options for running the test suite are summarized below.

As entry point the API landing page of an OGC API - Tiles instance is expected.

=== 1. Integrated development environment (IDE)

Use a Java IDE such as Eclipse, NetBeans, or IntelliJ. Clone the repository and build the project.

Set the main class to run: `org.opengis.cite.ogcapitiles10.TestNGController`

Arguments: The first argument must refer to an XML properties file containing the
required test run arguments. If not specified, the default location at `$
{user.home}/test-run-props.xml` will be used.

You can modify the sample file in `src/main/config/test-run-props.xml`

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties version="1.0">
  <comment>Test run arguments</comment>
  <entry key="iut">https://www.ldproxy.nrw.de/rest/services/kataster/</entry>
</properties>
----

The TestNG results file (`testng-results.xml`) will be written to a subdirectory
in `${user.home}/testng/` having a UUID value as its name.

=== 2. Command shell (console)

One of the build artifacts is an "all-in-one" JAR file that includes the test
suite and all of its dependencies; this makes it very easy to execute the test
suite in a command shell:

`java -jar ets-ogcapi-tiles10-${version}-aio.jar [-o|--outputDir $TMPDIR] [test-run-props.xml]`

=== 3. Docker (while at Alpha stage)

The test suite can be built and run by executing the following commands from a linux/MacOS terminal:

```
 git clone https://github.com/opengeospatial/ets-ogcapi-tiles10.git
 cd ets-ogcapi-tiles10
 mvn clean install -Dsource=8  docker:run -Pdocker
```
The `mvn` command will start a docker container running the ETS. Once the ETS is running, you can access it at http://localhost:8081/teamengine 

NOTE: This process has been tested with Java 11, Docker 24.0.5, and Maven 3.8.7.

=== 4. OGC test harness

Use https://github.com/opengeospatial/teamengine[TEAM Engine], the official OGC test harness.
The latest test suite release are usually available at the http://cite.opengeospatial.org/te2/[beta testing facility].
You can also https://github.com/opengeospatial/teamengine[build and deploy] the test
harness yourself and use a local installation.
